// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWXoS3Ct2iId_yKqCONcscMoUoaf831Tg',
    appId: '1:364502559229:web:81c6471381552780ae5194',
    messagingSenderId: '364502559229',
    projectId: 'production-3ee69',
    authDomain: 'production-3ee69.firebaseapp.com',
    storageBucket: 'production-3ee69.firebasestorage.app',
    measurementId: 'G-24RKH0K52J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvTgHRn5DLcz9F67hDYvk19-LTRrLjnXA',
    appId: '1:364502559229:android:79f34b8009538e20ae5194',
    messagingSenderId: '364502559229',
    projectId: 'production-3ee69',
    storageBucket: 'production-3ee69.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_miyVQVQY5b6pWj7Eau7XNXU-1p3d1qM',
    appId: '1:364502559229:ios:7b552f022001e915ae5194',
    messagingSenderId: '364502559229',
    projectId: 'production-3ee69',
    storageBucket: 'production-3ee69.firebasestorage.app',
    iosBundleId: 'com.example.aivlmIc',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_miyVQVQY5b6pWj7Eau7XNXU-1p3d1qM',
    appId: '1:364502559229:ios:7b552f022001e915ae5194',
    messagingSenderId: '364502559229',
    projectId: 'production-3ee69',
    storageBucket: 'production-3ee69.firebasestorage.app',
    iosBundleId: 'com.example.aivlmIc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWXoS3Ct2iId_yKqCONcscMoUoaf831Tg',
    appId: '1:364502559229:web:aad8525cfd31af54ae5194',
    messagingSenderId: '364502559229',
    projectId: 'production-3ee69',
    authDomain: 'production-3ee69.firebaseapp.com',
    storageBucket: 'production-3ee69.firebasestorage.app',
    measurementId: 'G-FGP9S6BJ01',
  );
}
