// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7yp5ZuUPEkwSRAz8g1aVaUT1zm-hF38',
    appId: '1:329690681345:web:3d841bf7b73d66f7873000',
    messagingSenderId: '329690681345',
    projectId: 'development-d0d1b',
    authDomain: 'development-d0d1b.firebaseapp.com',
    storageBucket: 'development-d0d1b.firebasestorage.app',
    measurementId: 'G-ELBG4KXBPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2olvqQfSdB4_kswdtwCWrUJolrc8Mg8',
    appId: '1:329690681345:android:e2d1cd8b1d2068b7873000',
    messagingSenderId: '329690681345',
    projectId: 'development-d0d1b',
    storageBucket: 'development-d0d1b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgW8KM7_5vDXaEz6SB8fDIop83X4tcBnY',
    appId: '1:329690681345:ios:4f1107bbdf4a4bec873000',
    messagingSenderId: '329690681345',
    projectId: 'development-d0d1b',
    storageBucket: 'development-d0d1b.firebasestorage.app',
    iosBundleId: 'com.example.aivlmIc',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgW8KM7_5vDXaEz6SB8fDIop83X4tcBnY',
    appId: '1:329690681345:ios:4f1107bbdf4a4bec873000',
    messagingSenderId: '329690681345',
    projectId: 'development-d0d1b',
    storageBucket: 'development-d0d1b.firebasestorage.app',
    iosBundleId: 'com.example.aivlmIc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7yp5ZuUPEkwSRAz8g1aVaUT1zm-hF38',
    appId: '1:329690681345:web:acd429124ca42d64873000',
    messagingSenderId: '329690681345',
    projectId: 'development-d0d1b',
    authDomain: 'development-d0d1b.firebaseapp.com',
    storageBucket: 'development-d0d1b.firebasestorage.app',
    measurementId: 'G-2MKGXZHQ02',
  );
}
