// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbitcmOh_YHwpBaHyFQj8CX7MiR6oI6A',
    appId: '1:682901480654:web:31a260e79310e2c5e21c9f',
    messagingSenderId: '682901480654',
    projectId: 'aivlm-ic',
    authDomain: 'aivlm-ic.firebaseapp.com',
    storageBucket: 'aivlm-ic.firebasestorage.app',
    measurementId: 'G-LMKYDW8MGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMyRWxH5RY87NHIBDWQvDUJrJ0qcP0Jqc',
    appId: '1:682901480654:android:ffddea8ed3c3be86e21c9f',
    messagingSenderId: '682901480654',
    projectId: 'aivlm-ic',
    storageBucket: 'aivlm-ic.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp8MGzbGj1luUiyfi1xiuBc3qvU6SzTN4',
    appId: '1:682901480654:ios:5d43c1c583d8a743e21c9f',
    messagingSenderId: '682901480654',
    projectId: 'aivlm-ic',
    storageBucket: 'aivlm-ic.firebasestorage.app',
    iosBundleId: 'com.example.aivlmIc',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp8MGzbGj1luUiyfi1xiuBc3qvU6SzTN4',
    appId: '1:682901480654:ios:5d43c1c583d8a743e21c9f',
    messagingSenderId: '682901480654',
    projectId: 'aivlm-ic',
    storageBucket: 'aivlm-ic.firebasestorage.app',
    iosBundleId: 'com.example.aivlmIc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwbitcmOh_YHwpBaHyFQj8CX7MiR6oI6A',
    appId: '1:682901480654:web:52065e5ab32c42b6e21c9f',
    messagingSenderId: '682901480654',
    projectId: 'aivlm-ic',
    authDomain: 'aivlm-ic.firebaseapp.com',
    storageBucket: 'aivlm-ic.firebasestorage.app',
    measurementId: 'G-N85VKS67V9',
  );
}
